// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial.Data;

namespace Parcial.Migrations
{
    [DbContext(typeof(DbReporte))]
    [Migration("20201006152333_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Parcial.Data.PersonaVehiculo", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoPersona")
                        .HasColumnType("TEXT");

                    b.Property<string>("CedulaPersona")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdReporteVehiculo2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LugarPersonaAtrapada")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePersona")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPersona");

                    b.ToTable("PersonaVe");

                    b.HasData(
                        new
                        {
                            IdPersona = 1,
                            IdReporteVehiculo2 = 0
                        });
                });

            modelBuilder.Entity("Parcial.Data.ReporteVehiculo", b =>
                {
                    b.Property<int>("IdReporteVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorVehiculo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarcaVehiculo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloVehiculo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaVehiculo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdReporteVehiculo");

                    b.ToTable("ReportesVe");

                    b.HasData(
                        new
                        {
                            IdReporteVehiculo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
